language: python
matrix:
  include:
    - name: "python 3 tests"
      python: "3.6"
      env: DJANGO_VERSION=2.2
    - name: "python 3 tests"
      python: "3.7"
      env: DJANGO_VERSION=3.0
    - name: "python 3 tests"
      python: "3.9"
      env: DJANGO_VERSION=4.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements/dev.txt
# command to run tests
script:
  - ./tests/manage.py test