language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0

matrix:
  exclude:
    - python: '3.6'
      env: DJANGO_VERSION=4.0
    - python: '3.7'
      env: DJANGO_VERSION=4.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements/dev.txt
# command to run tests
script:
  - ./tests/manage.py test
